In [5]:
import numpy as np
#Argmax: Returns the indices of the maximum values along an axis.
a = np.arange(6).reshape(2,3) + 10
print(a)
np.argmax(a)

[[10 11 12]
 [13 14 15]]


5

In [28]:
a = np.array((1,2,3))
b = np.array((2,3,4))
in_a = set(a)
in_b = set(b)
in_b_but_not_in_a = in_b - in_a
# print(in_b_but_not_in_a)
array = np.array(list(in_b_but_not_in_a))
# print(array.dtype)
result =np.concatenate((a,array))
print(result)

[1 2 3 4]


In [13]:
a = np.random.rand(10,256,256,20)
a.shape

(10, 256, 256, 20)

In [14]:
b = np.argmax(a, axis = -1)

In [15]:
print(b.shape)

(10, 256, 256)


In [ ]:
#if you don't want to do data augmentation, set data_gen_args as an empty dict.
#data_gen_args = dict()

data_gen_args = dict(rotation_range=0.2,
                    width_shift_range=0.05,
                    height_shift_range=0.05,
                    shear_range=0.05,
                    zoom_range=0.05,
                    horizontal_flip=True,
                    fill_mode='nearest')
myGenerator = trainGenerator(20,'data/membrane/train','image','label',data_gen_args,save_to_dir = "data/membrane/train/aug")

In [ ]:
load_data(...)

In [1]:
from segmentation_models import Unet
from segmentation_models.backbones import get_preprocessing
from segmentation_models.losses import bce_jaccard_loss
from segmentation_models.metrics import iou_score

BACKBONE = 'resnet34'
preprocess_input = get_preprocessing(BACKBONE)

# load your data
x_train, y_train, x_val, y_val = load_data(...)

# preprocess input
x_train = preprocess_input(x_train)
x_val = preprocess_input(x_val)

# define model
model = Unet(BACKBONE)
model.compile('Adam', loss=bce_jaccard_loss, metrics=[iou_score])

# fit model
# if you use data generator use model.fit_generator(...) instead of model.fit(...)
# more about `fit_generator` here: https://keras.io/models/sequential/#fit_generator
model.fit(
    x=x_train,
    y=y_train,
    batch_size=16,
    epochs=100,
    validation_data=(x_val, y_val),
)

Using TensorFlow backend.
/home/yifan/anaconda2/envs/tf3.6/lib/python3.6/site-packages/classification_models/resnext/__init__.py:4: UserWarning: Current ResNext models are deprecated, use keras.applications ResNeXt models
  warnings.warn('Current ResNext models are deprecated, '


NameError: name 'load_data' is not defined

In [28]:
import numpy as np
nb_classes = 6
data = [[2, 3, 4, 0],[1,2,3,4]]
data = np.array(data)
print(data.shape)

def indices_to_one_hot(data, shape, nb_classes):
    """Convert an iterable of indices to one-hot encoded labels."""
    targets = np.array(data).reshape(-1)
    return np.eye(nb_classes)[targets].reshape((shape[0],shape[1],nb_classes))

(2, 4)


In [29]:
result = np.eye(nb_classes)[data]

In [33]:
print(result[0,0])

[0. 0. 1. 0. 0. 0.]


In [24]:
print(a.shape)

(2, 4, 20)


In [10]:
print(a.reshape((4,2,20)))

[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
